package com.yunshi.kongfu.entity;

import java.util.ArrayList;
import java.util.List;

public class RoseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kongfu_rose
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kongfu_rose
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kongfu_rose
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kongfu_rose
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    public RoseExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kongfu_rose
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kongfu_rose
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kongfu_rose
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kongfu_rose
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kongfu_rose
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kongfu_rose
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kongfu_rose
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kongfu_rose
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kongfu_rose
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kongfu_rose
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table kongfu_rose
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andRosecodeIsNull() {
            addCriterion("roseCode is null");
            return (Criteria) this;
        }

        public Criteria andRosecodeIsNotNull() {
            addCriterion("roseCode is not null");
            return (Criteria) this;
        }

        public Criteria andRosecodeEqualTo(String value) {
            addCriterion("roseCode =", value, "rosecode");
            return (Criteria) this;
        }

        public Criteria andRosecodeNotEqualTo(String value) {
            addCriterion("roseCode <>", value, "rosecode");
            return (Criteria) this;
        }

        public Criteria andRosecodeGreaterThan(String value) {
            addCriterion("roseCode >", value, "rosecode");
            return (Criteria) this;
        }

        public Criteria andRosecodeGreaterThanOrEqualTo(String value) {
            addCriterion("roseCode >=", value, "rosecode");
            return (Criteria) this;
        }

        public Criteria andRosecodeLessThan(String value) {
            addCriterion("roseCode <", value, "rosecode");
            return (Criteria) this;
        }

        public Criteria andRosecodeLessThanOrEqualTo(String value) {
            addCriterion("roseCode <=", value, "rosecode");
            return (Criteria) this;
        }

        public Criteria andRosecodeLike(String value) {
            addCriterion("roseCode like", value, "rosecode");
            return (Criteria) this;
        }

        public Criteria andRosecodeNotLike(String value) {
            addCriterion("roseCode not like", value, "rosecode");
            return (Criteria) this;
        }

        public Criteria andRosecodeIn(List<String> values) {
            addCriterion("roseCode in", values, "rosecode");
            return (Criteria) this;
        }

        public Criteria andRosecodeNotIn(List<String> values) {
            addCriterion("roseCode not in", values, "rosecode");
            return (Criteria) this;
        }

        public Criteria andRosecodeBetween(String value1, String value2) {
            addCriterion("roseCode between", value1, value2, "rosecode");
            return (Criteria) this;
        }

        public Criteria andRosecodeNotBetween(String value1, String value2) {
            addCriterion("roseCode not between", value1, value2, "rosecode");
            return (Criteria) this;
        }

        public Criteria andRosenameIsNull() {
            addCriterion("roseName is null");
            return (Criteria) this;
        }

        public Criteria andRosenameIsNotNull() {
            addCriterion("roseName is not null");
            return (Criteria) this;
        }

        public Criteria andRosenameEqualTo(String value) {
            addCriterion("roseName =", value, "rosename");
            return (Criteria) this;
        }

        public Criteria andRosenameNotEqualTo(String value) {
            addCriterion("roseName <>", value, "rosename");
            return (Criteria) this;
        }

        public Criteria andRosenameGreaterThan(String value) {
            addCriterion("roseName >", value, "rosename");
            return (Criteria) this;
        }

        public Criteria andRosenameGreaterThanOrEqualTo(String value) {
            addCriterion("roseName >=", value, "rosename");
            return (Criteria) this;
        }

        public Criteria andRosenameLessThan(String value) {
            addCriterion("roseName <", value, "rosename");
            return (Criteria) this;
        }

        public Criteria andRosenameLessThanOrEqualTo(String value) {
            addCriterion("roseName <=", value, "rosename");
            return (Criteria) this;
        }

        public Criteria andRosenameLike(String value) {
            addCriterion("roseName like", value, "rosename");
            return (Criteria) this;
        }

        public Criteria andRosenameNotLike(String value) {
            addCriterion("roseName not like", value, "rosename");
            return (Criteria) this;
        }

        public Criteria andRosenameIn(List<String> values) {
            addCriterion("roseName in", values, "rosename");
            return (Criteria) this;
        }

        public Criteria andRosenameNotIn(List<String> values) {
            addCriterion("roseName not in", values, "rosename");
            return (Criteria) this;
        }

        public Criteria andRosenameBetween(String value1, String value2) {
            addCriterion("roseName between", value1, value2, "rosename");
            return (Criteria) this;
        }

        public Criteria andRosenameNotBetween(String value1, String value2) {
            addCriterion("roseName not between", value1, value2, "rosename");
            return (Criteria) this;
        }

        public Criteria andUsercodeIsNull() {
            addCriterion("userCode is null");
            return (Criteria) this;
        }

        public Criteria andUsercodeIsNotNull() {
            addCriterion("userCode is not null");
            return (Criteria) this;
        }

        public Criteria andUsercodeEqualTo(String value) {
            addCriterion("userCode =", value, "usercode");
            return (Criteria) this;
        }

        public Criteria andUsercodeNotEqualTo(String value) {
            addCriterion("userCode <>", value, "usercode");
            return (Criteria) this;
        }

        public Criteria andUsercodeGreaterThan(String value) {
            addCriterion("userCode >", value, "usercode");
            return (Criteria) this;
        }

        public Criteria andUsercodeGreaterThanOrEqualTo(String value) {
            addCriterion("userCode >=", value, "usercode");
            return (Criteria) this;
        }

        public Criteria andUsercodeLessThan(String value) {
            addCriterion("userCode <", value, "usercode");
            return (Criteria) this;
        }

        public Criteria andUsercodeLessThanOrEqualTo(String value) {
            addCriterion("userCode <=", value, "usercode");
            return (Criteria) this;
        }

        public Criteria andUsercodeLike(String value) {
            addCriterion("userCode like", value, "usercode");
            return (Criteria) this;
        }

        public Criteria andUsercodeNotLike(String value) {
            addCriterion("userCode not like", value, "usercode");
            return (Criteria) this;
        }

        public Criteria andUsercodeIn(List<String> values) {
            addCriterion("userCode in", values, "usercode");
            return (Criteria) this;
        }

        public Criteria andUsercodeNotIn(List<String> values) {
            addCriterion("userCode not in", values, "usercode");
            return (Criteria) this;
        }

        public Criteria andUsercodeBetween(String value1, String value2) {
            addCriterion("userCode between", value1, value2, "usercode");
            return (Criteria) this;
        }

        public Criteria andUsercodeNotBetween(String value1, String value2) {
            addCriterion("userCode not between", value1, value2, "usercode");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNull() {
            addCriterion("userName is null");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("userName is not null");
            return (Criteria) this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("userName =", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("userName <>", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("userName >", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("userName >=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("userName <", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("userName <=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("userName like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("userName not like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameIn(List<String> values) {
            addCriterion("userName in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotIn(List<String> values) {
            addCriterion("userName not in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("userName between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("userName not between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("userId is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("userId is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(Integer value) {
            addCriterion("userId =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(Integer value) {
            addCriterion("userId <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(Integer value) {
            addCriterion("userId >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("userId >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(Integer value) {
            addCriterion("userId <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(Integer value) {
            addCriterion("userId <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<Integer> values) {
            addCriterion("userId in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<Integer> values) {
            addCriterion("userId not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(Integer value1, Integer value2) {
            addCriterion("userId between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(Integer value1, Integer value2) {
            addCriterion("userId not between", value1, value2, "userid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table kongfu_rose
     *
     * @mbggenerated do_not_delete_during_merge Mon Jan 29 10:26:27 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table kongfu_rose
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}