package com.yunshi.kongfu.entity;

public class Rose {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kongfu_rose.id
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kongfu_rose.roseCode
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    private String rosecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kongfu_rose.roseName
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    private String rosename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kongfu_rose.userCode
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    private String usercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kongfu_rose.userName
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kongfu_rose.userId
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    private Integer userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kongfu_rose.id
     *
     * @return the value of kongfu_rose.id
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kongfu_rose.id
     *
     * @param id the value for kongfu_rose.id
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kongfu_rose.roseCode
     *
     * @return the value of kongfu_rose.roseCode
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    public String getRosecode() {
        return rosecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kongfu_rose.roseCode
     *
     * @param rosecode the value for kongfu_rose.roseCode
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    public void setRosecode(String rosecode) {
        this.rosecode = rosecode == null ? null : rosecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kongfu_rose.roseName
     *
     * @return the value of kongfu_rose.roseName
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    public String getRosename() {
        return rosename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kongfu_rose.roseName
     *
     * @param rosename the value for kongfu_rose.roseName
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    public void setRosename(String rosename) {
        this.rosename = rosename == null ? null : rosename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kongfu_rose.userCode
     *
     * @return the value of kongfu_rose.userCode
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    public String getUsercode() {
        return usercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kongfu_rose.userCode
     *
     * @param usercode the value for kongfu_rose.userCode
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    public void setUsercode(String usercode) {
        this.usercode = usercode == null ? null : usercode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kongfu_rose.userName
     *
     * @return the value of kongfu_rose.userName
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kongfu_rose.userName
     *
     * @param username the value for kongfu_rose.userName
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kongfu_rose.userId
     *
     * @return the value of kongfu_rose.userId
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kongfu_rose.userId
     *
     * @param userid the value for kongfu_rose.userId
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }
}