package com.yunshi.kongfu.entity;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kongfu_user.id
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kongfu_user.userCode
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    private String usercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kongfu_user.userName
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kongfu_user.userNick
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    private String usernick;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kongfu_user.password
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kongfu_user.job
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    private Integer job;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kongfu_user.userPower
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    private Integer userpower;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kongfu_user.phone
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kongfu_user.qq
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kongfu_user.sex
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kongfu_user.old
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    private Integer old;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kongfu_user.id
     *
     * @return the value of kongfu_user.id
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kongfu_user.id
     *
     * @param id the value for kongfu_user.id
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kongfu_user.userCode
     *
     * @return the value of kongfu_user.userCode
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    public String getUsercode() {
        return usercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kongfu_user.userCode
     *
     * @param usercode the value for kongfu_user.userCode
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    public void setUsercode(String usercode) {
        this.usercode = usercode == null ? null : usercode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kongfu_user.userName
     *
     * @return the value of kongfu_user.userName
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kongfu_user.userName
     *
     * @param username the value for kongfu_user.userName
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kongfu_user.userNick
     *
     * @return the value of kongfu_user.userNick
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    public String getUsernick() {
        return usernick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kongfu_user.userNick
     *
     * @param usernick the value for kongfu_user.userNick
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    public void setUsernick(String usernick) {
        this.usernick = usernick == null ? null : usernick.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kongfu_user.password
     *
     * @return the value of kongfu_user.password
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kongfu_user.password
     *
     * @param password the value for kongfu_user.password
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kongfu_user.job
     *
     * @return the value of kongfu_user.job
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    public Integer getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kongfu_user.job
     *
     * @param job the value for kongfu_user.job
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    public void setJob(Integer job) {
        this.job = job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kongfu_user.userPower
     *
     * @return the value of kongfu_user.userPower
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    public Integer getUserpower() {
        return userpower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kongfu_user.userPower
     *
     * @param userpower the value for kongfu_user.userPower
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    public void setUserpower(Integer userpower) {
        this.userpower = userpower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kongfu_user.phone
     *
     * @return the value of kongfu_user.phone
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kongfu_user.phone
     *
     * @param phone the value for kongfu_user.phone
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kongfu_user.qq
     *
     * @return the value of kongfu_user.qq
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kongfu_user.qq
     *
     * @param qq the value for kongfu_user.qq
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kongfu_user.sex
     *
     * @return the value of kongfu_user.sex
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kongfu_user.sex
     *
     * @param sex the value for kongfu_user.sex
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kongfu_user.old
     *
     * @return the value of kongfu_user.old
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    public Integer getOld() {
        return old;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kongfu_user.old
     *
     * @param old the value for kongfu_user.old
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    public void setOld(Integer old) {
        this.old = old;
    }
}