package com.yunshi.kongfu.mapper;

import com.yunshi.kongfu.entity.User;
import com.yunshi.kongfu.entity.UserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kongfu_user
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    int countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kongfu_user
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kongfu_user
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kongfu_user
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kongfu_user
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kongfu_user
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kongfu_user
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kongfu_user
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kongfu_user
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kongfu_user
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kongfu_user
     *
     * @mbggenerated Mon Jan 29 10:26:27 CST 2018
     */
    int updateByPrimaryKey(User record);

    List<User> queryLoginByUserName(String userName);
}